# Generated by Django 4.1.5 on 2023-01-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.CharField(default="SOME STRING", max_length=10000),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.CharField(default="SOME STRING", max_length=1000),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_content",
            field=models.TextField(default="SOME STRING", max_length=100000000000),
        ),
    ]
